
import { store } from '../../store.js';

class ArborModalCertificateView extends HTMLElement {
    connectedCallback() {
        this.render();
    }

    close() {
        store.setModal(null);
    }

    render() {
        const ui = store.ui;
        const moduleId = store.value.modal.moduleId;

        // Retrieve version hash from bookmark if available to verify content state
        const node = store.findNode(moduleId);
        const bookmark = node ? store.getBookmark(node.id, node.content) : null;
        const versionId = bookmark ? bookmark.hash.substring(0, 8).toUpperCase() : 'LEGACY';

        // --- DYNAMIC AUTHORITY NAME LOGIC ---
        // Reads from the 'universeName' property in data.json which is set by the builder
        // based on content/meta.json.
        
        const rawData = store.value.rawGraphData || {};
        const activeSource = store.value.activeSource || {};
        
        let authorityName = ui.certSign; // Default Fallback
        
        // 1. Prioritize Internal Data Name (Set by Builder via content/meta.json)
        if (rawData.universeName && rawData.universeName !== "Arbor Standard Curriculum") {
            authorityName = rawData.universeName;
        } 
        // 2. Fallback to Source Name (Set in Source Manager)
        else if (activeSource.name) {
            authorityName = activeSource.name;
        }

        const content = `
        <div class="p-12 text-center bg-yellow-50 dark:bg-yellow-950/20 h-full flex flex-col items-center justify-center relative overflow-hidden">
             <div class="absolute inset-0 border-[12px] border-double border-yellow-200 dark:border-yellow-900/40 m-6 rounded-3xl pointer-events-none"></div>
             
             <!-- Watermark / Background Logo -->
             <div class="absolute text-[18rem] opacity-5 pointer-events-none select-none text-slate-400 rotate-12">🎓</div>

             <div class="w-28 h-28 bg-white dark:bg-slate-900 rounded-full flex items-center justify-center text-6xl shadow-xl border-4 border-yellow-400 mb-8 relative z-10">
                ${node?.icon || '🎓'}
             </div>
             
             <h2 class="font-black text-3xl md:text-4xl text-slate-800 dark:text-white mb-2 uppercase tracking-[0.2em] relative z-10">${ui.certTitle}</h2>
             <div class="w-32 h-1.5 bg-yellow-400 mb-8 relative z-10 rounded-full"></div>
             
             <p class="text-slate-600 dark:text-slate-300 mb-4 font-serif italic text-xl relative z-10">${ui.certBody}</p>
             
             <h3 class="font-bold text-3xl md:text-5xl text-purple-600 dark:text-purple-400 mb-12 relative z-10 max-w-2xl leading-tight font-serif">
                ${node?.name || moduleId}
             </h3>
             
             <div class="flex gap-16 md:gap-32 text-center text-sm text-slate-400 font-mono relative z-10 uppercase tracking-widest">
                <div>
                    <div class="border-b-2 border-slate-300 dark:border-slate-700 pb-2 mb-2 w-40 mx-auto text-slate-700 dark:text-slate-300 font-bold text-lg">
                        ${new Date().toLocaleDateString()}
                    </div>
                    ${ui.certDate}
                </div>
                <div>
                    <div class="border-b-2 border-slate-300 dark:border-slate-700 pb-2 mb-2 w-56 mx-auto font-black text-slate-800 dark:text-white truncate text-lg">
                        ${authorityName}
                    </div>
                    ${ui.certSign}
                </div>
             </div>
             
             <div class="mt-auto mb-4 flex flex-col gap-1 items-center opacity-60 hover:opacity-100 transition-opacity">
                 <div class="text-[10px] text-slate-300 dark:text-slate-600 font-mono uppercase tracking-widest">
                     VERIFICATION ID: ${versionId}
                 </div>
                 <div class="text-[9px] text-slate-300 dark:text-slate-600">
                     Generated by Arbor UI
                 </div>
             </div>
             
             <button id="btn-print" class="absolute bottom-8 right-8 px-6 py-3 bg-slate-900 dark:bg-slate-800 text-white rounded-xl font-bold text-sm uppercase tracking-wider hover:scale-105 transition-transform shadow-xl flex items-center gap-2 print:hidden">
                <span>🖨️</span> ${ui.printCert}
             </button>
        </div>`;

        // Increased to max-w-4xl for Landscape format
        this.innerHTML = `
        <div id="modal-backdrop" class="fixed inset-0 z-[70] flex items-center justify-center bg-slate-900/80 backdrop-blur-sm p-4 animate-in fade-in">
            <div class="bg-white dark:bg-slate-900 rounded-[2rem] shadow-2xl max-w-4xl w-full relative overflow-hidden flex flex-col max-h-[90vh] aspect-[1.414/1] border border-slate-200 dark:border-slate-800 cursor-auto transition-all duration-300">
                <button class="btn-close absolute top-6 right-6 w-10 h-10 flex items-center justify-center rounded-full bg-slate-100 dark:bg-slate-800 hover:bg-red-50 dark:hover:bg-red-900/30 text-slate-400 hover:text-red-500 z-50 transition-colors print:hidden">✕</button>
                ${content}
            </div>
        </div>`;

        this.querySelector('.btn-close').onclick = () => this.close();
        this.querySelector('#btn-print').onclick = () => window.print();
    }
}
customElements.define('arbor-modal-certificate-view', ArborModalCertificateView);
